### PR TITLE
Parallel

### PR DESCRIPTION
**Pull request by slowkow**
This pull request modifies `RunCRE_HSAStringDB()` to use [BiocParallel].

[BiocParallel]: https://github.com/Bioconductor/BiocParallel

Here is the performance I got for 1 run with 1, 2, 4, 6, or 8 processes.

rplot

Unfortunately, the progress bar is not visible anymore.

After merging this pull request, you can still run the code on a single process:

```r
register(SerialParam(progressbar = TRUE))

RunCRE_HSAStringDB(...)
```

Or you can take advantage of multiple cores, servers, etc. with BiocParallel:

```r
register(MulticoreParam(workers = 4))

RunCRE_HSAStringDB(...)
```

### CODE REVIEW

**Comment by slowkow** [comment]
@carltonyfakhry Hey Carl, could I ask if you are interested to merge this pull request?

**Comment by slowkow** [comment]
Now that I'm running this package on my own data, I have noticed something.

When a result is very significant, it takes a very long time to compute the p-value (hours).

My pull request uses 1 process to compute the p-value for each regulator. This is great when all of the regulators have weak p-values, but not when we have a strong p-value. The strong p-value will be computed over many hours by a single process.

Instead, we might consider using multiple processes to compute the p-value for each regulator. This would have to be implemented in the C++ code, not in the R code. Since I haven't studied the code closely, I can't tell if this is possible or not.

What do you think?

**Comment by carltonyfakhry** [comment]
@slowkow I am typically slow to respond to pull requests as I am busy at work.

The code you have committed is missing changes to the documentation and vignette. As a general rule, I would require updating the documentation as a prerequisite to accepting pull requests.

**Comment by carltonyfakhry** [comment]
I would highly recommend reading through my [paper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-1181-8) for an algorithmic description of QuaternaryProd. The bottleneck in the algorithm is not the number of regulators but in the exponentially large sample space which is searched when computing the p-value. The algorithm in the paper proposes an approach to alleviate some of the bottleneck however the space remains large.
It might be possible to do C++ code optimization here, but that would require significant changes to the core code of QuaternaryProd. This will be very difficult to implement unless one has intimate knowledge of the algorithm and enough time to properly implement a maintainable piece of code.

**Comment by carltonyfakhry** [comment]
Also, notice that you are using the `only.significant.pvalues = TRUE` option which tells `RunCRE_HSAStringDB` to stop computing the p-value of a regulator as soon as the p-value is determined to be greater than the significance level. This is also a reason why you are observing the performance improvement when you have many weak p-values.

**Comment by carltonyfakhry** [comment]
Unfortunately, due to the reasons outlined in my previous comments, I cannot accept this pull request.

**Pull request closed without merging**
